### ISSUE TITLE
Python 3.5.2 and 3.5.3 have different magics.

### ISSUE THREAD

**Issue by socketpair** [matwey/rpmlint#1]
According to current code, `_python_magic_values` maps version to magic. Unfortunatelly, Python 3.5.2 and 3.5.3 has different magics (3350 and 3351 respectively).
1. But directory is the same -- `3.5`.
2. Current code don't have any magics for 3.5.x either. but Debian's version works for 3.5...

**Comment by matwey** [comment]
Could you please report issues upstream: https://github.com/rpm-software-management/rpmlint

**Comment by socketpair** [comment]
Sorry, I thought this is upstream.....
